---
namespace: ashimov
name: rke2_ansible
version: 1.0.0
readme: README.md
authors:
  - ashimov
description: Collection for ashimov/rke2-ansible

license_file: 'LICENSE'

tags: [infrastructure, linux, kubernetes, rancher, rke2]

repository: https://github.com/ashimov/rke2-ansible
documentation: https://github.com/ashimov/rke2-ansible
homepage: https://github.com/ashimov/rke2-ansible
issues: https://github.com/ashimov/rke2-ansible/issues

build_ignore:
  - tarball_install/*
  - testing
  - .github
